services:
    db:
        container_name: wish-database
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminpass
            - POSTGRES_DB=wish
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    smtp:
        container_name: wish-smtp
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - "5000:80"
            - "2525:25"
        volumes:
            - smtp_data:/smtp4dev

volumes:
    db_data:
    smtp_data:
